// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try {
  process.loadEnvFile?.();
} catch {
  // Ignore if unsupported
}
import path from 'path';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: path.join('prisma'),
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node -r tsconfig-paths/register prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
