export const AUTH_ROUTES = {
  LOGIN: 'login',
  REFRESH: 'refresh',
  LOGOUT: 'logout',
  LOGOUT_ALL: 'logout-all',
  FORGOT_PASSWORD: 'forgot-password',
  VALIDATE_TOKEN: 'validate-token',
  RESET_PASSWORD: 'reset-password',
  CHANGE_PASSWORD: 'change-password',
  PASSWORD_SET: 'password/set',
  GOOGLE: 'google',
  GOOGLE_CALLBACK: 'google/callback',
  OAUTH_EXCHANGE: 'oauth/exchange',
  OTP_SEND: 'otp/send',
  OTP_VERIFY: 'otp/verify',
} as const;
